#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : metrics-discovery
Version  : 1.5.95
Release  : 1
URL      : https://github.com/intel/metrics-discovery/archive/metrics-discovery-1.5.95.tar.gz
Source0  : https://github.com/intel/metrics-discovery/archive/metrics-discovery-1.5.95.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: metrics-discovery-lib
BuildRequires : cmake
BuildRequires : mesa-dev
Patch1: 0001-cmake-Set-lib-version-property-based-on-header-data.patch
Patch2: 0002-Create-and-install-a-PC-file-for-pkg-config.patch
Patch3: 0003-Refer-LIB_INSTALL_DIR-and-LIB_SUFFIX-for-installatio.patch

%description
# Intel(R) Metrics Discovery Application Programming Interface
## Introduction
This software is a user mode library that provides access to GPU performance data.

%package dev
Summary: dev components for the metrics-discovery package.
Group: Development
Requires: metrics-discovery-lib
Provides: metrics-discovery-devel

%description dev
dev components for the metrics-discovery package.


%package lib
Summary: lib components for the metrics-discovery package.
Group: Libraries

%description lib
lib components for the metrics-discovery package.


%prep
%setup -q -n metrics-discovery-metrics-discovery-1.5.95
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528276964
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DMD_PLATFORM=linux -DMD_BUILD_TYPE=release
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1528276964
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mdapi/metrics_discovery_api.h
/usr/lib64/libmd.so
/usr/lib64/pkgconfig/libmd.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmd.so.1
/usr/lib64/libmd.so.1.5.95
